# 🧪 Staging Environment Configuration
# TDD Framework - Staging Settings (Pre-Production)

[app]
name = "TDD Framework (Staging)"
environment = "staging"
debug = false
version = "1.0.0-staging"
host = "0.0.0.0"
port = 8501

[database]
framework_db_path = "/app/data/framework.db"
timer_db_path = "/app/data/task_timer.db"
connection_timeout = 15
pool_size = 4
max_overflow = 8

# Staging database optimizations
enable_wal_mode = true
cache_size = -2000  # 2MB cache
temp_store = "memory"

[security]
require_auth = true  # Authentication required in staging
csrf_token_expiry = 3600  # 1 hour
session_timeout_minutes = 240  # 4 hours (shorter than dev)
cookie_name = "tdd_framework_session_staging"

# Enhanced security for staging
enable_rate_limiting = true
enable_dos_protection = true
enable_log_sanitization = true
log_level = "INFO"

[performance]
enable_database_cache = true
cache_ttl_seconds = 300  # 5 minutes
enable_redis = false  # Redis optional in staging
redis_url = ""  # Will be set via environment variable if needed

# Pagination settings
default_page_size = 50
max_page_size = 500

# Streamlit optimization
enable_streamlit_cache = true

[monitoring]
enable_health_check = true  # Health checks enabled
health_check_port = 8080
enable_metrics = true  # Basic metrics in staging
metrics_port = 9090

# Structured logging for staging
log_format = "json"
enable_correlation_ids = true
log_file_path = "/app/logs/tdd_framework.log"

[google_oauth]
# These MUST be set via environment variables:
# GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET
client_id = ""  # Set via GOOGLE_CLIENT_ID
client_secret = ""  # Set via GOOGLE_CLIENT_SECRET
redirect_uri = "https://staging.tdd-framework.com"
scopes = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile"
]